import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RootNavbarLayout from "@/layout/RootLayout";
import {
  ClerkProvider,
} from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "JokiinAja",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <meta title="JokiinAja" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}
        >
          <RootNavbarLayout>{children}</RootNavbarLayout>
        </body>
      </html>
    </ClerkProvider>
  );
}
