import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RootNavbarLayout from "@/layout/RootLayout";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "JokiinAja",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <title>JokiinAja</title>
          <link rel="icon" href="/favicon-icon/JokiinAja-3.png" type="image/png" />

          {/* <!-- Open Graph (Facebook, WA, dll) --> */}
          <meta property="og:title" content="JokiinAja" />
          <meta property="og:description" content="Website Jokiin Tugas" />
          <meta property="og:image" content="https://jokiin-aja-io.vercel.app/favicon-icon/JokiinAja-3.png" />
          <meta property="og:url" content="https://jokiin-aja-io.vercel.app" />
          <meta property="og:type" content="website" />

          {/* <!-- Twitter Card --> */}
          <meta name="twitter:card" content="summary_large_image" />
          <meta name="twitter:title" content="JokiinAja" />
          <meta name="twitter:description" content="Website Jokiin Tugas" />
          <meta name="twitter:image" content="https://jokiin-aja-io.vercel.app/favicon-icon/JokiinAja-3.png" />
        </head>

        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}
        >
          <RootNavbarLayout>{children}</RootNavbarLayout>
        </body>
      </html>
    </ClerkProvider>
  );
}
